target_sources(
  obs-studio
  PRIVATE
    settings/QCiBasicSettings_A11y.cpp
    settings/QCiBasicSettings_Appearance.cpp
    settings/QCiBasicSettings_Stream.cpp
    settings/QCiBasicSettings.cpp
    settings/QCiBasicSettings.hpp
    settings/QCiHotkeyEdit.cpp
    settings/QCiHotkeyEdit.hpp
    settings/QCiHotkeyLabel.cpp
    settings/QCiHotkeyLabel.hpp
    settings/QCiHotkeyWidget.cpp
    settings/QCiHotkeyWidget.hpp
)
